### ISSUE TITLE
absoluteで表示させているテキストがファーストビューで流れて表示されてしまう

### ISSUE THREAD

**Issue by yoko-web** [yoko-web/sakurai-piano-school#8]
<img width="342" alt="Screenshot 2022-07-25 at 17 28 38" src="https://user-images.githubusercontent.com/97857877/180733156-d2077b52-42e6-4f23-97bb-b1050b8bf01d.png">

**Comment by yoko-at-home** [comment]
a11a1e1655bdb73df4803c98178e4014d1575dd5にて修正済み
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/09/30/07/cf637ea1-d0bc-4b40-87cc-382f0ca7e20d.webp)](https://lgtmeow.com)
